server.port: 8082

spring:
  jpa:
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

  application:
    name: podcasts-ms

  datasource:
    url: jdbc:mysql://localhost:3306/podcasts?useSSL=false&user=root&password=000315



logging.level:
  root: WARN
  com.example.mediabase.podcastsui: DEBUG

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000